[package]
name = "curly-giggle"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.4"

[[bench]]
name = "bm_sds"
harness = false

[features]

default = []

full = [
    "collection",
]

collection = [
]